- hosts: dev[0]
  user: mdm
  connection: ssh
  become: yes
  tasks: 
     - name: create new deployment
       command: kubectl apply -f /home/mdm/deployment.yml
     - name: create new service
       command: kubectl apply -f /home/mdm/service.yml